name = "WebDAV"
uuid = "27d30f90-6b5f-11e9-3518-5beabd086426"
authors = ["Alexander Barth <barth.alexander@gmail.com>"]
version = "0.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
